### ISSUE TITLE
Tobotdriver crashes after running a few cycles

### ISSUE THREAD

**Issue by Megacephalo** [MalcolmMielle/Tobot#3]
I was running the Tobotdriver for a while now and it does not happen at first, but after repeated usage of say, a month, every time the program runs for a few cycles, it freezes at the stage with the messages on the terminal:

``` C++
wrote the demand 3GN
written
```

and I realized these two messages represent the beginning of a new cycle, however, the node stops at this point. What may be the problem? Is there something to do with the memory buffer?

**Comment by Megacephalo** [comment]
I am sorry and embarrassed to have posted this issue and there is no way of deleting it. Your program is perfect. The phenomenon actually came from the corrupted RS232-USB emulator cable communicating between the driver and the CPU. Thank you !

**Comment by MalcolmMielle** [comment]
No worries, opening issues to just find out the solution right after happened to me before as well :). Hardware errors are tricky.
I'll close this issue.

Glad to hear TobotDriver is of help to you. If you have other issues with it don't hesitate to ask.

**Comment by MalcolmMielle** [comment]
I wanted to tell you, in case you are using only the driver for the Faulhabber controller here is the repository with only this : https://github.com/MalcolmMielle/driver_differential_drive
